name:                aoc20
version:             0.1.0.0
github:              "mvaldesdeleon/aoc20"
license:             BSD3
author:              "Martin Valdes de Leon"
maintainer:          "m.valdesdeleon@gmail.com"
copyright:           "Copyright (c) 2020 Martin Valdes de Leon"

extra-source-files:
- README.md
- ChangeLog.md

data-files:
- inputs/*.txt

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mvaldesdeleon/aoc20#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- vector
- containers
- lens
- listsafe
- monad-loops
- parsec
- ListZipper
- ansi-terminal
- split

ghc-options:
#- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions: []

library:
  source-dirs: src
  generated-other-modules: Paths_aoc20

executables:
  day1:
    main:                Day1Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Day1Main
    - -O2
    dependencies:
    - aoc20
    other-modules:
    - Paths_aoc20
  day2:
    main:                Day2Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Day2Main
    - -O2
    dependencies:
    - aoc20
    other-modules:
    - Paths_aoc20
  day3:
    main:                Day3Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Day3Main
    - -O2
    dependencies:
    - aoc20
    other-modules:
    - Paths_aoc20
  day4:
    main:                Day4Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Day4Main
    - -O2
    dependencies:
    - aoc20
    other-modules:
    - Paths_aoc20
  day5:
    main:                Day5Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Day5Main
    - -O2
    dependencies:
    - aoc20
    other-modules:
    - Paths_aoc20
  day6:
    main:                Day6Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Day6Main
    - -O2
    dependencies:
    - aoc20
    other-modules:
    - Paths_aoc20
  day7:
    main:                Day7Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Day7Main
    - -O2
    dependencies:
    - aoc20
    other-modules:
    - Paths_aoc20

tests:
  aoc20-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc20
